/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:11aa4650-ce60-4d60-b20b-298984b91f85",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8pWpVZcSt",
    "aws_user_pools_web_client_id": "1p2g2m4sndtcbmv1eb0d2ihs3u",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": "us-east-2",
        "userPoolId": "us-east-2_VIcIDaBTH",
        "userPoolWebClientId": "k6vk6qcj7p734toefre05d3rq",
        "mandatorySignIn": true
    }
};


export default awsmobile;
